name = "Problox"
uuid = "41531fc7-7f15-48cd-9c2f-2efb66d9fe65"
authors = ["McCoy R. Becker <mccoybecker@gmail.com>"]
version = "0.1.0"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
Conda = "1.4"
MacroTools = "0.5"
PyCall = "1.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
